### ISSUE TITLE
Backend Connection

### ISSUE THREAD

**Issue by TabotCharlesBessong** [TabotCharlesBessong/MERNPROJECTS#12]
## Feature Description

[Describe the new feature you'd like to see in detail. Provide relevant context and any specific requirements or constraints.]
- [x] Create backend folder
- [x] Initializing NPM Project
- [x] Copy data.ts to backend/src
- [x] npm install express cors
- [x] Create .gitignore
- [x] Create server.js
  - [x] Add & Config Express
    - [x] Add & Config Cors
  - [x] Add Food Router
    - [x] Add jsconfig.json
    - [x] Add Apis
- [x] npm install nodemon
  - [x] Add dev Script into the package.json
  - [x] npm run dev
- [x] Add axios package
  - [x] axiosConfig.js file
- [x] Connect food service to the Apis
## Why is this feature needed?

[Explain the problem or use case that this feature would address.]

## Proposed Solution

[Provide a high-level overview of your proposed solution or any ideas you have for implementing the feature.]

## Additional Information (optional)

[Add any additional information or context about the feature request.]

**Comment by saisreesatyassss** [comment]
hello 
i tried to slove the problems in food delivery but there is nothing in that code it was just some starting code only no pages or anything

**Comment by TabotCharlesBessong** [comment]
Hello thank you your help. There nothing done there yet. I just created
those issues as task I have to do.
Go to the food_ordering_app branch you will have the most up to date stable
code. On the search branch you will see the latest codes.

There I have an a bug when I try searching


You could help me with that

Thank you
